<?php
add_action( 'init', 'custom_post_types' );
function custom_post_types() {

	register_post_type('team', array(
		'label'  => _x( 'Our team', 'Post type general name', 'textdomain' ),
		'labels' => array(
			'name'               => _x( 'Team', 'Post type general name', 'textdomain' ),
			'singular_name'      => _x( 'Team', 'Post type general name', 'textdomain' ),
			'add_new'            => __( 'Add', 'textdomain' ),
			'add_new_item'       => __( 'Add', 'textdomain' ),
			'edit_item'          => __( 'Edit', 'textdomain' ),
			'new_item'           => __( 'New', 'textdomain' ),
			'view_item'          => __( 'View', 'textdomain' ),
			'search_items'       => __( 'Search', 'textdomain' ),
			'not_found'          => __( 'No found.', 'textdomain' ),
			'not_found_in_trash' => __( 'No found in Trash.', 'textdomain' ),
			'parent_item_colon'  => __( 'Parent', 'textdomain' ),
			'menu_name'          => _x( 'Our team', 'Post type general name', 'textdomain' )
		),
		'description'         => '',
		'public'              => true,
		'publicly_queryable'  => true,
		'show_ui'             => true,
		'show_in_rest'        => true,
		'rest_base'           => '',
		'show_in_menu'        => true,
		'exclude_from_search' => false,
		'capability_type'     => 'post',
		'map_meta_cap'        => true,
		'hierarchical'        => true,
		'rewrite'             => true,
		'has_archive'         => false,
		'query_var'           => true,
		'supports'            => array( 'title', 'editor', 'thumbnail', 'excerpt', 'page-attributes'),
		'taxonomies'          => array(),
	) );

	register_post_type('practices', array(
		'label'  => _x( 'Practices', 'textdomain' ),
		'labels' => array(
			'name'               => _x( 'Practices', 'Post type general name', 'textdomain' ),
			'singular_name'      => _x( 'Practices', 'Post type general name', 'textdomain' ),
			'add_new'            => __( 'Add', 'textdomain' ),
			'add_new_item'       => __( 'Add', 'textdomain' ),
			'edit_item'          => __( 'Edit', 'textdomain' ),
			'new_item'           => __( 'New', 'textdomain' ),
			'view_item'          => __( 'View', 'textdomain' ),
			'search_items'       => __( 'Search', 'textdomain' ),
			'not_found'          => __( 'No found.', 'textdomain' ),
			'not_found_in_trash' => __( 'No found in Trash.', 'textdomain' ),
			'parent_item_colon'  => __( 'Parent', 'textdomain' ),
			'menu_name'          => _x( 'Practices', 'Post type general name', 'textdomain' )
		),
		'description'         => '',
		'public'              => true,
		'publicly_queryable'  => true,
		'show_ui'             => true,
		'show_in_rest'        => true,
		'rest_base'           => '',
		'show_in_menu'        => true,
		'exclude_from_search' => false,
		'capability_type'     => 'post',
		'map_meta_cap'        => true,
		'hierarchical'        => true,
		'rewrite'             => true,
		'has_archive'         => false,
		'query_var'           => true,
		'supports'            => array( 'title', 'editor', 'thumbnail', 'excerpt', 'page-attributes'),
		'taxonomies'          => array(),
	) );

	register_post_type('reference', array(
		'label'  => _x( 'References', 'textdomain' ),
		'labels' => array(
			'name'               => _x( 'References', 'Post type general name', 'textdomain' ),
			'singular_name'      => _x( 'References', 'Post type general name', 'textdomain' ),
			'add_new'            => __( 'Add', 'textdomain' ),
			'add_new_item'       => __( 'Add', 'textdomain' ),
			'edit_item'          => __( 'Edit', 'textdomain' ),
			'new_item'           => __( 'New', 'textdomain' ),
			'view_item'          => __( 'View', 'textdomain' ),
			'search_items'       => __( 'Search', 'textdomain' ),
			'not_found'          => __( 'No found.', 'textdomain' ),
			'not_found_in_trash' => __( 'No found in Trash.', 'textdomain' ),
			'parent_item_colon'  => __( 'Parent', 'textdomain' ),
			'menu_name'          => _x( 'References', 'Post type general name', 'textdomain' )
		),
		'description'         => '',
		'public'              => false,
		'publicly_queryable'  => false,
		'show_ui'             => true,
		'show_in_rest'        => true,
		'rest_base'           => '',
		'show_in_menu'        => true,
		'exclude_from_search' => false,
		'capability_type'     => 'post',
		'map_meta_cap'        => true,
		'hierarchical'        => true,
		'rewrite'             => true,
		'has_archive'         => false,
		'query_var'           => true,
		'supports'            => array( 'title', 'editor', 'thumbnail', 'page-attributes'),
		'taxonomies'          => array(),
	) );

	register_post_type('job', array(
		'label'  => _x( 'Jobs', 'textdomain' ),
		'labels' => array(
			'name'               => _x( 'Jobs', 'Post type general name', 'textdomain' ),
			'singular_name'      => _x( 'Jobs', 'Post type general name', 'textdomain' ),
			'add_new'            => __( 'Add', 'textdomain' ),
			'add_new_item'       => __( 'Add', 'textdomain' ),
			'edit_item'          => __( 'Edit', 'textdomain' ),
			'new_item'           => __( 'New', 'textdomain' ),
			'view_item'          => __( 'View', 'textdomain' ),
			'search_items'       => __( 'Search', 'textdomain' ),
			'not_found'          => __( 'No found.', 'textdomain' ),
			'not_found_in_trash' => __( 'No found in Trash.', 'textdomain' ),
			'parent_item_colon'  => __( 'Parent', 'textdomain' ),
			'menu_name'          => _x( 'Jobs', 'Post type general name', 'textdomain' )
		),
		'description'         => '',
		'public'              => true,
		'publicly_queryable'  => true,
		'show_ui'             => true,
		'show_in_rest'        => true,
		'rest_base'           => '',
		'show_in_menu'        => true,
		'exclude_from_search' => false,
		'capability_type'     => 'post',
		'map_meta_cap'        => true,
		'hierarchical'        => true,
		'rewrite'             => true,
		'has_archive'         => false,
		'query_var'           => true,
		'supports'            => array( 'title', 'editor', 'thumbnail', 'page-attributes'),
		'taxonomies'          => array(),
	) );

}